service: nestjs-serverless-demo-api

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    API_URI: ${env:API_URI}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
